### ISSUE TITLE
Diacritcs on capital letters

### ISSUE THREAD

**Issue by dgcampbe** [Donnnno/Arcticons-Font#1]
I am unable to type (I am testing it out in LibreOffice) capital letters such as "Ä" or "É" with the diacritics. They appear as "A" and "E". The lowercase versions are fine. Example where this is a potential problem: since nouns are capitalized in German, any noun starting with umlauts will have them missing (like Übersetzer).
Now for a language nut rant:
Also, as a language nerd I noticed the lack of the German Eszett (ß) or the cedilla diacritic (used in French and Portuguese). These are probably more than necessary as "ß" is often replaced with "ss" and as far as I know "ç" can be replaced with "c" if necessary. Additionally, it isn't even close to possible to cover all 50 zillion characters in a font like this, but I want to complain since I am a language nut. 😛

**Comment by Donnnno** [comment]
Included in the latest release :)
