### ISSUE TITLE
[Language] Cyrillic

### ISSUE THREAD

**Issue by alabotski** [Donnnno/Arcticons-Font#3]
Is it possible add russian symbols?

**Comment by Donnnno** [comment]
Hey, yes we do have cryrilic glyphs, but I haven't updated this file in ages. Check out: https://github.com/Donnnno/Arcticons/blob/main/templates/arcticons_font.svg

**Comment by Donnnno** [comment]
Hi again, I've updated the font to include Cyrillic glyphs. It doesn't include proper kerning right now, but feel free to leave any feedback!

https://github.com/Donnnno/Arcticons-Font/releases/tag/0.500

**Comment by Donnnno** [comment]
Marking this one as completed, if you encounter any bugs, please update me in a new issue :)
